# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt requirements.txt

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container
COPY . .

# Expose the port on which the Flask app will run
EXPOSE 5000

# Train the model and save the pickle file
RUN python machine_learning.py

# Define the command to run the Flask app
CMD ["python", "app.py"]
